=head1 How do I...

=head2 How do I get data from a database?

DBI, and its DBD children, like DBD::SQLite

=head2 How do I get data from a web page?

LWP stands for "libwww-perl", and is the standard way of talking
to web pages.

WWW::Mechanize is a superset of LWP that makes HTML processing
easier.

=head2 How do I do date calculations?

Use C<Date::Manip>, C<Date::Calc> or C<DateTime>.  All have different
styles and different capabilities.

=head2 How do I handle command-line arguments in my program?

Use C<Getopt::Long>.

=head2 How do I write CGI programs?

Use C<CGI>.

=head2 How do I parse HTML?

Whatever you do, don't use regular expressions.  Use C<HTML::Parser>
or one of the many classes that uses it.  Look around on
L<http://search.cpan.org>.

If you're parsing HTML so that you can extract links or images from
a web page, use C<WWW::Mechanize> which handles it for you.

=head2 How do I parse XML?

See the list of Recommended XML Modules at the Perl 5 wiki.

L<http://www.perlfoundation.org/perl5/index.cgi?recommended_xml_modules>

=head2 How do I know if a URL is valid?

=head2 How do I do screen access?

=head2 How do I do colors?

=head2 How do I do readkey?

=head2 How do I do passwords?
