=head1 Where to get Perl

=head2 Do you have Perl?

Try typing "perl -v" at the command line.  You should get a version
statement.

    $ perl -v

    This is perl 5, version 16, subversion 1 (v5.16.1) built for
    darwin-thread-multi-2level
    ....

=head2 Perl source

L<http://www.cpan.org/src>

You will need a compiler, a shell, and some system libraries.  Perl's
C<Configure> script will tell you if you're missing something.

If you're on Windows, you may not have a compiler to use.  Look
onward to Strawberry or ActiveState.

=head2 Windows Perl: Strawberry

L<http://www.strawberryperl.com>

Strawberry Perl is a Windows Perl distribution that
comes with a CPAN client, a working compiler and a lot of modules
already pre-installed.

Unless you have a very specific need, you want the Strawberry Perl
distribution.

=head2 Windows Perl: ActiveState

Originators of Perl on Windows, and still very much involved in the
community, ActiveState releases their own version of Perl with a
module installation system called PPM.  If you don't want to deal with
the "hassle" of managing your Perl install yourself, this may be for you.
