=head1 Things to do here at perl101.org

=head2 Handle Perl 6

Ultimately I'd like to have perl101 show both the Perl 6 and Perl
5 ways of doing things.  This way we show new people to Perl 6 how
to do things, and can also act as a Perl 5-to-Perl 6 phrasebook.

=head1 Site functionality

=head2 Include the FAQ

=head2 Link page

=head2 Feedback per page

=head2 Explain use strict

In the debugging page, we say to use warnings and strict always.  Explain why.

=head2 precedence

or/and vs ||/&&
